ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL013_G.bam ./output/FELINE_bam/P13_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL014_G.bam ./output/FELINE_bam/P14_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL015_G.bam ./output/FELINE_bam/P15_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL019_G.bam ./output/FELINE_bam/P19_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL020_G.bam ./output/FELINE_bam/P20_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL021_G.bam ./output/FELINE_bam/P21_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL022_G.bam ./output/FELINE_bam/P22_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL023_G.bam ./output/FELINE_bam/P23_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL025_G.bam ./output/FELINE_bam/P25_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL026_G.bam ./output/FELINE_bam/P26_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL027_G.bam ./output/FELINE_bam/P27_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL028_G.bam ./output/FELINE_bam/P28_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL029_G.bam ./output/FELINE_bam/P29_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL031_G.bam ./output/FELINE_bam/P31_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL034_G.bam ./output/FELINE_bam/P34_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL035_G.bam ./output/FELINE_bam/P35_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL036_G.bam ./output/FELINE_bam/P36_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL037_G.bam ./output/FELINE_bam/P37_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL039_G.bam ./output/FELINE_bam/P39_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL041_G.bam ./output/FELINE_bam/P41_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL043_G.bam ./output/FELINE_bam/P43_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL044_G.bam ./output/FELINE_bam/P44_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL045_G.bam ./output/FELINE_bam/P45_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL046_G.bam ./output/FELINE_bam/P46_G.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL013_S.bam ./output/FELINE_bam/P13_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL014_S.bam ./output/FELINE_bam/P14_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL015_S.bam ./output/FELINE_bam/P15_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL019_S.bam ./output/FELINE_bam/P19_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL020_S.bam ./output/FELINE_bam/P20_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL021_S.bam ./output/FELINE_bam/P21_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL022_S.bam ./output/FELINE_bam/P22_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL023_S.bam ./output/FELINE_bam/P23_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL025_S.bam ./output/FELINE_bam/P25_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL026_S.bam ./output/FELINE_bam/P26_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL027_S.bam ./output/FELINE_bam/P27_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL028_S.bam ./output/FELINE_bam/P28_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL029_S.bam ./output/FELINE_bam/P29_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL031_S.bam ./output/FELINE_bam/P31_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL034_S.bam ./output/FELINE_bam/P34_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL035_S.bam ./output/FELINE_bam/P35_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL036_S.bam ./output/FELINE_bam/P36_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL037_S.bam ./output/FELINE_bam/P37_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL039_S.bam ./output/FELINE_bam/P39_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL041_S.bam ./output/FELINE_bam/P41_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL043_S.bam ./output/FELINE_bam/P43_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL044_S.bam ./output/FELINE_bam/P44_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL045_S.bam ./output/FELINE_bam/P45_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL046_S.bam ./output/FELINE_bam/P46_S.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL013_E.bam ./output/FELINE_bam/P13_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL014_E.bam ./output/FELINE_bam/P14_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL015_E.bam ./output/FELINE_bam/P15_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL019_E.bam ./output/FELINE_bam/P19_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL020_E.bam ./output/FELINE_bam/P20_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL021_E.bam ./output/FELINE_bam/P21_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL022_E.bam ./output/FELINE_bam/P22_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL023_E.bam ./output/FELINE_bam/P23_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL025_E.bam ./output/FELINE_bam/P25_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL026_E.bam ./output/FELINE_bam/P26_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL027_E.bam ./output/FELINE_bam/P27_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL028_E.bam ./output/FELINE_bam/P28_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL029_E.bam ./output/FELINE_bam/P29_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL031_E.bam ./output/FELINE_bam/P31_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL034_E.bam ./output/FELINE_bam/P34_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL035_E.bam ./output/FELINE_bam/P35_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL036_M.bam ./output/FELINE_bam/P36_M.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL037_E.bam ./output/FELINE_bam/P37_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL039_E.bam ./output/FELINE_bam/P39_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL041_E.bam ./output/FELINE_bam/P41_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL043_E.bam ./output/FELINE_bam/P43_E.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL044_M.bam ./output/FELINE_bam/P44_M.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL045_M.bam ./output/FELINE_bam/P45_M.bam
ln -s /home/jichen/Projects/Breast/scRNA/FELINE/FELINE_merged_011_040_premrna/VariantCalls_bam/output/FELINE_bam/FEL046_M.bam ./output/FELINE_bam/P46_M.bam
